tidy up zen garden
anthony-xiao/sprint-2 pull request #1
Opened 2018-03-31 23:57 UTC by anthony-xiao

Went through the whole file to make indentation where it seems fit.

2018-04-09 00:39 UTC, bronburgundy requested changes
Please @ me when done. Thanks :)

2018-04-09 00:39 UTC, bronburgundy commented on pristine-zen-garden.html
> +                        View All Designs</a></li>
This should be on line above :)

2018-04-09 00:39 UTC, bronburgundy commented on pristine-zen-garden.html
> +                        Submit a Design</a></li>
Same with this one.

2018-04-09 07:21 UTC, merged

2018-04-09 07:22 UTC, anthony-xiao commented
@bronburgundy thanks for the suggestion. definitely missed by me there. Changes are now merged

2018-04-10 03:38 UTC, bronburgundy commented
@anthony-xiao I think I'm being a bit slow... but how do I view your changes to sign off on it?

2018-04-11 06:53 UTC, anthony-xiao commented
I believe once i have merged it (its done so you are good to go) you will delete the tidying branch then your DONE!